### PR TITLE
feat: Added data and initial preprocessing file to merge datasets

### PR DESCRIPTION
**Pull request by maheshjindal**
# Description

Added the preprocessing Jupyter Notebook file and relevant datasets responsible for preprocessing raw datasets and merge them. This feature won't impact any other modules in any terms.

Fixes # (issue if any): N/A

## Type of change
1. Added a Jupyter Notebook responsible for preprocessing and merging multiple raw datasets.
2. Added the raw datasets and preprocessed datasets (for reference).

- [x] New feature (non-breaking change which adds functionality)

## Have you tested end to end changes on your local?

- [x] Yes

## Additional Notes (if any)
The size of merged dataset is huge(~80Mb), that's why have not been added to this repository.

### CODE REVIEW

**Review by rjrahul24 — APPROVED** [review]

**Review by rjrahul24 — APPROVED** [review]

**Comment by guptaparth25** [comment]
I think we should just post the link to the google drive folder instead of the dataset itself because we might have to change it.

**Review by ayushbaral — APPROVED** [review]
Looks fine to me.

**Comment by maheshjindal** [comment]
> I think we should just post the link to the google drive folder instead of the dataset itself because we might have to change it.

@guptaparth25 , we have not committed our final or any merged dataset into this repo. These are the only initial/raw versions.

**Review by prerit44 — APPROVED** [review]
lgtm

**Review by guptaparth25 — APPROVED** [review]
lgtm!

**Pull request merged**
